export const queryKeys = {
  addresses: 'addresses',
  collections: 'collections',
  collectionProducts: 'collectionProducts',
  collectionPosters: 'collectionPosters',
  countries: 'countries',
  country: 'country',
  frames: 'frames',
  products: 'products',
  productOptions: 'productOptions',
  users: 'users',
  posters: 'posters',
  featuredPosters: 'featuredPosters',
  productCountryOptions: 'productCountryOptions',
  translations: 'translations',
  productImages: 'productImages',
  productPrices: 'productPrices',
  searchPosters: 'searchPosters',
  postersByIDs: 'postersByIDs',
  ordersByToken: 'ordersByToken',
  prices: 'prices',
};
