// The keys for the correct translations
export const TRX = {
  COMMON:{
    BRAND: "pages.brand",
    SIZE: "pages.product-size",
    QUANTITY: "pages.product-quantity",
    NEXT: "instaprint.app.modal.next",
    PREV: "instaprint.app.modal.prev",

  },
  PRODUCT_DETAILS: {
    INFORMATION: 'pages.product-information',
    DESCRIPTION: 'pages.product-description',
    ADDITIONAL_DETAILS: 'pages.additional-details',
    ADD_TO_CART: 'pages.add-to-cart',
    SIZE: 'pages.product-size',
    CHOOSE_FRAME: 'pages.product-frame-selection',
  },
  BLOG: {
    META_TITLE: 'blog.meta-title',
    META_DESCRIPTION: 'blog.meta-description',
    TITLE: 'blog.title',
    DESCRIPTION: 'blog.description',
  },
  CART: {
    error: 'pages.error',
  },
  ORDER: {
    ORDER: 'orders.order',
    NUMBER: 'orders.order-number',
    DATE: 'orders.order-date',
    STATUS: 'orders.order-status',
    TOTAL: 'orders.order-total',
    DETAILS: 'orders.order-details',
    SHIPPING: 'orders.order-shipping',
    SUCCESSFUL: 'orders.order-successful',
    SUCCESSFUL_MESSAGE: 'orders.order-successful-message',
    FAILED_MESSAGE: 'orders.failed-message',
    TRACKING_NUMBER: 'orders.order-tracking-number',
  },
  INSTAPRINT: {
    META_TITLE: 'instaprint.meta.title',
    META_DESCRIPTION: 'instaprint.meta.description',
    HERO_TITLE: "instaprint.hero.title",
    HERO_DESCRIPTION: "instaprint.hero.description",
    HERO_CTA: "instaprint.hero.cta",
    SECTION1_TITLE: "instaprint.section1.title",
    SECTION1_DESCRIPTION: "instaprint.section1.description",
    SECTION1_IMAGE: "instaprint.section1.image",
    SECTION2_TITLE: "instaprint.section2.title",
    SECTION2_DESCRIPTION: "instaprint.section2.description",
    SECTION2_IMAGE: "instaprint.section2.image",
    APP_MODAL_TITLE: "instaprint.app.modal.title",
    APP_MODAL_DESCRIPTION: "instaprint.app.modal.description",
    APP_MODAL_IMAGE: "instaprint.app.modal.image",
    APP_MODAL_NEXT: "instaprint.app.modal.next",
    APP_MODAL_PREV: "instaprint.app.modal.prev",
    APP_MODAL_ADD_CART: "instaprint.app.modal.addcart",
    APP_MODAL_NONSELECTED: "instaprint.app.modal.nonselected",
    APP_MODAL_SELECTION_TITLE: "instaprint.app.modal.selection.title",
    APP_MODAL_SELECTION_DESCRIPTION: "instaprint.app.modal.selection.description",
    APP_MODAL_SELECTION_VARIATION1_TITLE: "instaprint.app.modal.selection.variations1.title",
    APP_MODAL_SELECTION_VARIATION1_DESCRIPTION: "instaprint.app.modal.selection.variations1.description",
    APP_MODAL_SELECTION_VARIATION1_FOOTNOTE: "instaprint.app.modal.selection.variations1.footnote",
    APP_MODAL_SELECTION_VARIATION2_TITLE: "instaprint.app.modal.selection.variations2.title",
    APP_MODAL_SELECTION_VARIATION2_DESCRIPTION: "instaprint.app.modal.selection.variations2.description",
    APP_MODAL_SELECTION_VARIATION2_FOOTNOTE: "instaprint.app.modal.selection.variations2.footnote",
    APP_MODAL_SIZE: "instaprint.app.modal.selection.size",
    APP_MODAL_PLACEHOLDER: "instaprint.app.modal.selection.placeholder",
    APP_MODAL_QUANTITY: "instaprint.app.modal.selection.quantity",
    APP_MODAL_SELECTED: "instaprint.app.modal.selected",
    APP_MODAL_CANCEL: "instaprint.app.modal.cancel",
  },
  PAYMENT_ERRORS: {
    '5062': 'paymentErrors.MISCALCULATED_SUM',
    '10051': 'paymentErrors.NOT_SUFFICIENT_FUNDS',
    '10005': 'paymentErrors.DO_NOT_HONOUR',
    '10012': 'paymentErrors.INVALID_TRANSACTION',
    '10041': 'paymentErrors.LOST_CARD',
    '10043': 'paymentErrors.STOLEN_CARD',
    '10054': 'paymentErrors.EXPIRED_CARD',
    '10084': 'paymentErrors.INVALID_CVC2',
    '10057': 'paymentErrors.NOT_PERMITTED_TO_CARDHOLDER',
    '10058': 'paymentErrors.NOT_PERMITTED_TO_TERMINAL',
    '10034': 'paymentErrors.FRAUD_SUSPECT',
    '10093': 'paymentErrors.RESTRICTED_BY_LAW',
    '10201': 'paymentErrors.CARD_NOT_PERMITTED',
    '10204': 'paymentErrors.UNKNOWN',
    '10206': 'paymentErrors.INVALID_CVC2_LENGTH',
    '10207': 'paymentErrors.REFER_TO_CARD_ISSUER',
    '10208': 'paymentErrors.INVALID_MERCHANT_OR_SP',
    '10209': 'paymentErrors.BLOCKED_CARD',
    '10210': 'paymentErrors.INVALID_CAVV',
    '10211': 'paymentErrors.INVALID_ECI',
    '10213': 'paymentErrors.BIN_NOT_FOUND',
    '10214': 'paymentErrors.COMMUNICATION_OR_SYSTEM_ERROR',
    '10215': 'paymentErrors.INVALID_CARD_NUMBER',
    '10216': 'paymentErrors.NO_SUCH_ISSUER',
    '10217': 'paymentErrors.DEBIT_CARDS_REQUIRES_3DS',
    '10219': 'paymentErrors.REQUEST_TIMEOUT',
    '10222': 'paymentErrors.NOT_PERMITTED_TO_INSTALLMENT',
    '10223': 'paymentErrors.REQUIRES_DAY_END',
    '10225': 'paymentErrors.RESTRICTED_CARD',
    '10226': 'paymentErrors.EXCEEDS_ALLOWABLE_PIN_TRIES',
    '10227': 'paymentErrors.INVALID_PIN',
    '10228': 'paymentErrors.ISSUER_OR_SWITCH_INOPERATIVE',
    '10229': 'paymentErrors.INVALID_EXPIRE_YEAR_MONTH',
    '10232': 'paymentErrors.INVALID_AMOUNT',
  },
};
