import { AboutView } from '@/views';
import Head from 'next/head';

export default function About() {
  return (
    <>
      <Head>
        <title>Open Digital Gallery | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AboutView />
      </main>
    </>
  );
}
