import {
  POSTERS_REFETCH_COUNT,
  queryKeys,
  queryStaleDuration,
  revalidateDuration,
} from '@/constants';
import { getCollections, getInfinitePosters } from '@/data/hooks';
import { getProductOptions } from '@/data/hooks/useProductOptions';
import { ArtPrintsView } from '@/views';
import { QueryClient, dehydrate } from '@tanstack/react-query';
import Head from 'next/head';

export default function ArtPrints() {
  return (
    <>
      <Head>
        <title>Art Prints</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ArtPrintsView />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const queryClient = new QueryClient();

  // Populate Cache : Featured List
  await queryClient.prefetchInfiniteQuery(
    [queryKeys.posters],
    () => getInfinitePosters({ from: 0, to: POSTERS_REFETCH_COUNT - 1 }),
    {
      staleTime: queryStaleDuration,
    }
  );

  // Populate Cache : Categories
  await queryClient.prefetchQuery([queryKeys.collections], () => getCollections(), {
    staleTime: queryStaleDuration,
  });

  // Populate Cache : Product Options For Chart
  await queryClient.prefetchQuery([queryKeys.productOptions], () => getProductOptions(), {
    staleTime: queryStaleDuration,
  });

  return {
    props: {
      dehydratedState: JSON.parse(JSON.stringify(dehydrate(queryClient))),
      revalidate: revalidateDuration,
    },
  };
};
