import { CartView } from '@/views';
import Head from 'next/head';
import 'leaflet/dist/leaflet.css';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import nextI18NextConfig from '@/../next-i18next.config';
import { LocaleType } from '@/types';
// import { I18N, LOCALES_LIST } from '@/constants';
// import { getProductDetailByHandle } from '@/data/hooks/useProductDetailByHandle';
// import { getProductOptions } from '@/data/hooks/useProductOptions';
// import { getFrames } from '@/data/hooks';

export default function Cart() {
  return (
    <>
      <Head>
        <title>Open Digital Gallery</title>
        <meta name="robots" content="noindex" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CartView />
      </main>
    </>
  );
}

export const getStaticProps = async ({ locale }: { locale: LocaleType }) => {
  // const localeValues = locale === LOCALES_LIST[0] ? I18N[LOCALES_LIST[0]] : I18N[LOCALES_LIST[1]];

  // const productData = product?.data?.length ? product.data[0] : {};
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'], nextI18NextConfig)),
    },
  };
};
