import {
  Button,
  MyLink,
  AnnouncementBanner,
  CollectionHero,
  SectionContainer,
  BodyL,
  BodyX,
  NewsletterBanner,
  FilterTab,
} from '@/components';
import { Footer } from '@/components/Layout';
import Head from 'next/head';

export default function Components() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" min-h-[100vh]">
        {/* Button Variants */}
        <SectionContainer className="flex flex-col gap-10 py-10">
          <h1 className="text-center border-1 border-solid w-full">Buttons</h1>
          <div className="flex gap-5 items-center">
            <Button text="Basic Button" />
            <Button text="Basic Button Light" variant="light" />
            <Button>
              <BodyX>Button With Children - Dark</BodyX>
            </Button>
            <Button variant="light">
              <BodyX>Button With Children - Light</BodyX>
            </Button>

            <Button text="Overrided Basic Button" className="h-16" />
          </div>
        </SectionContainer>

        {/* Links Variants */}
        <SectionContainer className="flex flex-col gap-10 py-10">
          <h1 className="text-center border-1 border-solid w-full">Links {'<a>'}</h1>
          <div className="flex gap-5 items-center">
            <MyLink href="/" text="Link" />
            <MyLink href="/" text="Link Light" variant="light" />
            <MyLink href="/">
              <BodyX>Link With Children - Dark</BodyX>
            </MyLink>
            <MyLink href="/" variant="light">
              <BodyX>Link With Children - Light</BodyX>
            </MyLink>

            <MyLink href="/" text="Overrided Basic Link" className="h-16" />
          </div>
        </SectionContainer>

        {/* Announcement Banner */}
        <SectionContainer className="flex flex-col gap-10 py-10">
          <h1 className="text-center border-1 border-solid w-full">Announcement Banner</h1>
          <AnnouncementBanner>
            <BodyL>Announcement Banner</BodyL>
          </AnnouncementBanner>
        </SectionContainer>

        {/* Category Card */}
        {/* <SectionContainer className="flex flex-col gap-10 py-10">
          <h1 className="text-center border-1 border-solid w-full">Collection Card</h1>
          <div className="grid grid-cols-3">
            <CollectionCard name="Originals" imgPath="/placeholder-product.jpg" />
          </div>
        </SectionContainer> */}

        {/* Collection Hero */}
        <SectionContainer className="flex flex-col gap-10 py-10 m-auto">
          <h1 className="text-center border-1 border-solid w-full">Collection Hero</h1>
          <CollectionHero
            name="Originals"
            description="Sadece Open Digital Gallery'de bulabileceğiniz art print ve poster ürünleri."
            linkText="Visit Collection"
            href="/"
            imgPath="/placeholder-product.jpg"
          />
        </SectionContainer>

        {/* Newsletter Banner */}
        <SectionContainer className="flex flex-col gap-10 py-10 m-auto">
          <h1 className="text-center border-1 border-solid w-full">
            Newsletter Banner (Not Finished)
          </h1>
          <NewsletterBanner
            headline="Stay up to date for new arrivals."
            description="Join our newsletter and stay up to date for new arrivals."
          />
        </SectionContainer>

        {/* Filter Tab */}
        <SectionContainer className="flex flex-col gap-10 py-10 m-auto">
          <h1 className="text-center border-1 border-solid w-full">Filter Tab</h1>
          <FilterTab />
        </SectionContainer>

        {/* Footer */}
        <Footer />
      </div>
    </>
  );
}
