import { queryKeys, queryStaleDuration, revalidateDuration } from '@/constants';
import { getCollections, getFrames } from '@/data/hooks';
import { getProductOptions } from '@/data/hooks/useProductOptions';
import { FramesView } from '@/views';
import { QueryClient, dehydrate } from '@tanstack/react-query';
import Head from 'next/head';

export default function Frames() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <FramesView />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const queryClient = new QueryClient();

  // Populate Cache : Frames
  await queryClient.prefetchQuery([queryKeys.frames], () => getFrames(), {
    staleTime: queryStaleDuration,
  });

  // Populate Cache : Categories
  await queryClient.prefetchQuery([queryKeys.collections], () => getCollections(), {
    staleTime: queryStaleDuration,
  });

  // Populate Cache : Product Options For Chart
  await queryClient.prefetchQuery([queryKeys.productOptions], () => getProductOptions(), {
    staleTime: queryStaleDuration,
  });

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
      revalidate: revalidateDuration,
    },
  };
};
