import React from 'react';
import Head from 'next/head';
import { CheckoutView } from '@/views';

export default function Checkout() {
  return (
    <>
      <Head>
        <title>Open Digital Gallery</title>
        <meta name="robots" content="noindex" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CheckoutView />
      </main>
    </>
  );
}
