import { useEffect } from 'react';
// import { CartView } from '@/views';
import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import nextI18NextConfig from '@/../next-i18next.config';
import { LocaleType } from '@/types';
import { PAGES } from '@/constants';
// import { InstaprintLandingPageView } from '@/views';
import { useRouter } from 'next/router';
import { instagramClient } from "@/data/instagramClient";
import { Loading } from '@/components';
// import { I18N, LOCALES_LIST } from '@/constants';
// import { getProductDetailByHandle } from '@/data/hooks/useProductDetailByHandle';
// import { getProductOptions } from '@/data/hooks/useProductOptions';
// import { getFrames } from '@/data/hooks';

export default function InstaPrintAuthPage() {
    const router = useRouter();
    const { query } = router;
    const { code } = query;
    console.log('code', code);

    async function getInstagramData() {
        if (code && typeof code === "string") {
            const igCode = code.replace("#_", "");
            if (code) {
                const token = await instagramClient.getAccessToken(igCode);
                console.log("ig auth page token", token)
                if (token) {
                    const mediaResponse = await instagramClient.getMedia(token);
                    if (mediaResponse.length) { }
                    router.push(PAGES.INSTAPRINT_APP.path);
                }
            }

        }
    }



    useEffect(() => {
        if (code) {
            getInstagramData();
        }
    },[code])

    return (
        <>
            <Head>
                <title>Open Digital Gallery</title>
                <meta name="robots" content="noindex" />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='min-w-[60vh]'>
                <Loading />
            </main>
        </>
    );
}

export const getStaticProps = async ({ locale }: { locale: LocaleType }) => {

    return {
        props: {
            ...(await serverSideTranslations(locale, ['common'], nextI18NextConfig)),
        },
    };
};
